name: CI

on:
  pull_request:

  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm ci (--ignore-scripts to disable husky on CI), audit, lint, test
        run: |
          npm ci --ignore-scripts
          npm audit
          npm run lint
          npm test
